### ISSUE TITLE
Initial text color

### ISSUE THREAD

**Issue by A1rPun** [LouisMazel/vue-input-ui#3]
So my browser theme makes all inputs on the page `background-color: black` and `color: white`. I noticed that you set a custom background-color (#fff white) but not a custom text-color.

Can you maybe remove the background color or add a text color?

So the inputs look like this:
![1564747701](https://user-images.githubusercontent.com/3754692/62369170-085e5100-b52f-11e9-9e90-26fb9a570223.png)

Oh and the "Valid input state" input has a missing `.is-dark` class in the Example.

**Comment by LouisMazel** [comment]
Solved in 1.*
