### ISSUE TITLE
Create @change event for input

### ISSUE THREAD

**Issue by danilsdf** [LouisMazel/vue-input-ui#30]
I cannot find a way to track changes(not by @Watch)

**Comment by LouisMazel** [comment]
Hey @danilsdf,

This library is outdated, please use: 
- Vue 3 : [maz-ui](https://louismazel.github.io/maz-ui-3/) and [MazInput](https://louismazel.github.io/maz-ui-3/components/maz-input.html) component
- Vue 2 : [maz-ui](https://louismazel.github.io/maz-ui/) and [MazInput](https://louismazel.github.io/maz-ui/documentation/maz-input) component
